# Generated by Django 3.2.4 on 2021-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20210614_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.TextField(default=1626925650.9482408),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
